# Generated by Django 4.1.7 on 2024-07-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0018_alter_booking_booking_date_alter_service_space_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='space_type',
            field=models.CharField(choices=[('Seat', 'S1'), ('Desk', 'D1'), ('Meeting Room', 'MR'), ('Conference Room', 'CR')], default='Day WorkStation', max_length=50, unique=True),
        ),
    ]
