# Generated by Django 4.1.7 on 2024-07-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0019_alter_service_space_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='space_type',
            field=models.CharField(choices=[('Seat1', 'S1'), ('Seat2', 'S2'), ('Seat3', 'S3'), ('Seat4', 'S4'), ('Seat5', 'S5'), ('Seat6', 'S6'), ('Seat7', 'S7'), ('Seat8', 'S8'), ('Seat9', 'S9'), ('Seat10', 'S10'), ('Seat11', 'S11'), ('Seat12', 'S12'), ('Seat13', 'S13'), ('Seat14', 'S14'), ('Seat15', 'S15'), ('Seat16', 'S16'), ('Seat17', 'S17'), ('Seat18', 'S18'), ('Seat19', 'S19'), ('Seat20', 'S20')], default='Day WorkStation', max_length=50, unique=True),
        ),
    ]
